//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.ExpressApp.DC;

using DevExpress.Persistent.Base;
using DevExpress.Xpo;
using QuickZ.Core.Contracts.Templates;
using System;

namespace QuickZ.Persistent.Xpo.BusinessObjects.Templates
{
    [DevExpress.ExpressApp.DC.DomainComponent]
    [NavigationItem(false), CreatableItem(true)]
    [XafDefaultProperty("DocumentName")]
    [ImageName("BOBusinessDocumentData")]    
    [DevExpress.ExpressApp.DC.XafDisplayName("File Attachments")]
    [FileAttachment("File")]
    public partial class QuickZFileTemplate : QuickZTemplateDocumentBase, IDocumentTemplate
    {

        public QuickZFileTemplate(Session session)
            : base(session)
        {
        }

        TemplateType IDocumentTemplate.TemplateType
        {
            get
            {
                return TemplateType.FileAttachment;
            }
        }
    }
}
